### ISSUE TITLE
[Tracking] Upgrading to v0.0.3

### ISSUE THREAD

**Issue by aahmde** [izu-mi/py-tensor#3]
### Version: 0.0.3 Update
Let's start to add v0.0.3 planned features

## TODO
- [ ] Train model with different datasets
- [ ] Generate graphs with predictions plotted on a chart
- [ ] Add docstrings to our code
- [ ] Clean up code presentation
